import type { Agent, CategoryOption, SortOption } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'degen-trader',
    name: 'DegenTrader',
    ticker: 'DEGEN',
    avatar: '🦍',
    description: 'Aggressive momentum trader specializing in memecoins. Apes in fast, exits faster.',
    tokenPrice: 0.00234,
    priceChange24h: 42.5,
    cycleCount: 1247,
    walletBalance: 0.156,
    status: 'active',
    category: 'trading',
  },
  {
    id: 'alpha-seeker',
    name: 'AlphaSeeker',
    ticker: 'ALPHA',
    avatar: '🔮',
    description: 'Scours Twitter and Discord for early alpha. First to spot emerging narratives.',
    tokenPrice: 0.00089,
    priceChange24h: -8.2,
    cycleCount: 892,
    walletBalance: 0.043,
    status: 'active',
    category: 'research',
  },
  {
    id: 'whale-watcher',
    name: 'WhaleWatcher',
    ticker: 'WHALE',
    avatar: '🐋',
    description: 'Monitors large wallet movements on-chain. Alerts when whales accumulate or dump.',
    tokenPrice: 0.00156,
    priceChange24h: 15.3,
    cycleCount: 2156,
    walletBalance: 0.089,
    status: 'active',
    category: 'analytics',
  },
  {
    id: 'copy-cat',
    name: 'CopyCat',
    ticker: 'COPY',
    avatar: '🐱',
    description: 'Mirrors the trades of top-performing wallets with a slight delay for safety.',
    tokenPrice: 0.00045,
    priceChange24h: -2.1,
    cycleCount: 567,
    walletBalance: 0.021,
    status: 'idle',
    category: 'trading',
  },
  {
    id: 'meme-lord',
    name: 'MemeLord',
    ticker: 'MEME',
    avatar: '👑',
    description: 'Creates viral memes about your bags. Pumps communities with engagement farming.',
    tokenPrice: 0.00789,
    priceChange24h: 128.7,
    cycleCount: 445,
    walletBalance: 0.234,
    status: 'active',
    category: 'social',
  },
  {
    id: 'snipe-bot',
    name: 'SnipeBot',
    ticker: 'SNIPE',
    avatar: '🎯',
    description: 'Lightning-fast new pair sniper. Gets in within seconds of liquidity add.',
    tokenPrice: 0.00012,
    priceChange24h: -45.2,
    cycleCount: 3421,
    walletBalance: 0.005,
    status: 'offline',
    category: 'trading',
  },
  {
    id: 'yield-farmer',
    name: 'YieldFarmer',
    ticker: 'YIELD',
    avatar: '🌾',
    description: 'Optimizes DeFi yields across protocols. Auto-compounds and rebalances positions.',
    tokenPrice: 0.00567,
    priceChange24h: 3.4,
    cycleCount: 1893,
    walletBalance: 0.445,
    status: 'active',
    category: 'defi',
  },
  {
    id: 'news-bot',
    name: 'NewsBot',
    ticker: 'NEWS',
    avatar: '📰',
    description: 'Aggregates crypto news and summarizes impact. First to know, first to trade.',
    tokenPrice: 0.00234,
    priceChange24h: 7.8,
    cycleCount: 756,
    walletBalance: 0.067,
    status: 'active',
    category: 'research',
  },
  {
    id: 'nft-hunter',
    name: 'NFTHunter',
    ticker: 'HUNT',
    avatar: '🎨',
    description: 'Scouts undervalued NFT collections. Snipes rare traits below floor.',
    tokenPrice: 0.00034,
    priceChange24h: -12.5,
    cycleCount: 234,
    walletBalance: 0.012,
    status: 'idle',
    category: 'nft',
  },
  {
    id: 'arb-master',
    name: 'ArbMaster',
    ticker: 'ARB',
    avatar: '⚡',
    description: 'Cross-DEX arbitrage specialist. Finds price discrepancies and profits instantly.',
    tokenPrice: 0.00678,
    priceChange24h: 22.1,
    cycleCount: 4567,
    walletBalance: 0.567,
    status: 'active',
    category: 'trading',
  },
];

export const categories: CategoryOption[] = [
  { value: 'all', label: 'All Categories' },
  { value: 'trading', label: 'Trading' },
  { value: 'research', label: 'Research' },
  { value: 'analytics', label: 'Analytics' },
  { value: 'social', label: 'Social' },
  { value: 'defi', label: 'DeFi' },
  { value: 'nft', label: 'NFT' },
];

export const sortOptions: SortOption[] = [
  { value: 'newest', label: 'Newest' },
  { value: 'most-active', label: 'Most Active' },
  { value: 'highest-volume', label: 'Highest Volume' },
  { value: 'price-change', label: 'Price Change' },
];
